PROXY_HOST = "localhost"
PROXY_PORT = 8000

CONSUMER_HOST = "localhost"
CONSUMER_PORT = 8001

MIN_PACKET_LENGTH = 1
MAX_PACKET_LENGTH = 100
PACKET_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

MIN_DELAY = 1.0
MAX_DELAY = 3.0

BIT_0_DELAY = 0.5
BIT_1_DELAY = 2.0
BIT_THRESHOLD = 1.25

LOG_FORMAT = "%(asctime)s - %(name)s - %(message)s"
LOG_LEVEL = "INFO"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
